<?php
// $Id$

/**
 * @file
 * Create Content Block (or node/add Block).
 */

function createcontentblock_init() {
  drupal_add_css(drupal_get_path('module', 'createcontentblock') . '/createcontentblock.css');
  drupal_add_js(drupal_get_path('module', 'createcontentblock') . '/createcontentblock.js');
}

/**
 * Implementation of hook_block().
 */
function createcontentblock_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['nodeadd'] = array(
        'info' => t('Create content'),
        'cache' => BLOCK_CACHE_PER_USER,
        'status' => 1,
        'region' => 'header_last',
      );
//      if (module_exists('og')) {
//        $blocks['og_nodeadd']['info'] = t('Create content in group');
//        $blocks['og_nodeadd']['cache'] = BLOCK_NO_CACHE;
//      }
      return $blocks;
      break;

    case 'configure':
      $form['use_javascript'] = array(
        '#type' => 'checkbox',
        '#title' => t('Collapse/expand block with javascript'),
        '#default_value' => variable_get("createcontentblock_use_javascript_$delta", TRUE),
        '#description' => t('Use javascript to make the form collapse'),
      );
      return $form;
      break;

    case 'save':

      variable_set("createcontentblock_use_javascript_$delta", $edit['use_javascript']);
      break;

    case 'view':
      if ($links = createcontentblock_getlinks($delta)) { // intentional assignment of $links
        $linkclass = variable_get("createcontentblock_use_javascript_$delta", TRUE) ? 'collapse' : 'nocollapse';
        $subject = t('Create');
        return array('subject' => $subject, 'content' => theme('links', $links, array('class' => "createcontentblock-links $linkclass")));
      }
      break;
  }
}

function createcontentblock_getlinks($delta) {
  $item = menu_get_item('node/add');
  $links = array();
  $menu_items = system_admin_menu_block($item);
  foreach ($menu_items as $menu_item) {
    $args = explode('/', $menu_item['href']);
    $type = str_replace('-', '_', array_pop($args));
    $title = $menu_item['title'];
    $menu_item['title'] = "<span class='icon node-{$type}'></span>{$menu_item['title']}";
    $menu_item['html'] = TRUE;
    $links["{$title}:{$type}"] = $menu_item;
  }
  ksort($links);
  return $links;
}

