<?php
// $Id$

/**
 * @file
 * Create Content Block (or node/add Block).
 */

/**
 * Implementation of hook_block().
 */
function createcontentblock_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks['nodeadd'] = array(
        'info' => t('Create content'),
        'cache' => module_exists('og') ? BLOCK_NO_CACHE : BLOCK_CACHE_PER_USER,
        'status' => 1,
        'region' => 'header_last',
      );
//      if (module_exists('og')) {
//        $blocks['og_nodeadd']['info'] = t('Create content in group');
//      }
      return $blocks;

    case 'configure':
      $form['use_javascript'] = array(
        '#type' => 'checkbox',
        '#title' => t('Collapse/expand block with javascript'),
        '#default_value' => variable_get("createcontentblock_use_javascript_$delta", TRUE),
        '#description' => t('Use javascript to make the form collapse'),
      );
      return $form;

    case 'save':

      foreach(element_children($edit) as $e) {
        variable_set("createcontentblock_$e", $edit[$e]);
      }

    case 'view':
      if ($links = createcontentblock_getlinks($delta)) {
        $subject = t('Create');
        if (variable_get('createcontentblock_use_javascript', TRUE)) {
          drupal_add_css(drupal_get_path('module', 'createcontentblock') . '/createcontentblock.css');
          drupal_add_js(drupal_get_path('module', 'createcontentblock') . '/createcontentblock.js');
          $subject = "<span class='icon'>+</span> <a href='/node/add'>$subject</a>";
        }
        return array('subject' => $subject, 'content' => theme('links', $links));
      }
  }
}

function createcontentblock_getlinks() {
  $item = menu_get_item('node/add');
  $links = array();
  foreach (system_admin_menu_block($item) as $menu_item) {
    $args = explode('/', $menu_item['href']);
    $type = str_replace('-', '_', array_pop($args));
    $menu_item['title'] = "<span class='icon node-{$type}'></span>{$menu_item['title']}";
    $menu_item['html'] = TRUE;
    $links["{$type}"] = $menu_item;
  }
  ksort($links);
  return $links;
}